### ISSUE TITLE
Add shoutcast support?

### ISSUE THREAD

**Issue by vext01** [carlosrafaelgn/FPlayAndroid#15]
Hey Carlos,

Me again. I've been using fplay on my phone for local media and now I see you have added radio support. Very awesome. I'm going to raise a couple of feature requests. Here is the first.

You already have support for icecast, which is very cool. Now how about shoutcast also? Then we can all listen to http://somafm.com/ in fplay!

**Comment by carlosrafaelgn** [comment]
Hi Edd!

Your suggestions are always welcome! :D 

Unfortunately, this time I don't think it will so easy to fix. FPlay can already handle a few shoutcast radios, through the button "Add URL", where you can manually add your radio's URL (this is how I do to listen to trance.fm).

In order to access their API, you need to become their partner first - http://www.shoutcast.com/Partners , unlike icecast, which is completely open and free.

I confess I haven't tried to become their "partner" yet, mostly because of what they say right above the contact form: "... we'll get back to you when we are ready to take on new partners." ... this doesn't sound very promising to me, what do you think?

Regards!!!

**Comment by carlosrafaelgn** [comment]
@vext01 I'm closing this, as I already managed to become a SHOUTcast partner :)
